import { HOME_PHOTOS } from "../home-media";
import type { TrustSnapshot } from "./types";

/**
 * Realistic seed for Trust System.
 * Swap this module for a DB/API adapter — types stay the same.
 */
export const TRUST_SNAPSHOT_SEED: TrustSnapshot = {
  updatedAt: "2026-08-06T07:00:00.000Z",
  metrics: {
    totalOrders: 4826,
    ordersToday: 12,
    averageRating: 4.9,
    reviewCount: 1634,
    repeatRate: 0.38,
    citiesLabel: "Красноярск и доставка по России",
  },
  latestOrders: [
    {
      id: "ord-live-01",
      giftId: "mug",
      giftTitle: "Кружка с акварельным портретом",
      giftHref: "/gift?id=mug",
      orderSameHref: "/gift?id=mug",
      recipientName: "Ольга",
      recipientRole: "Мама",
      total: 2490,
      completedAt: "2026-07-28",
      completedLabel: "28 июля",
      photoUrl: HOME_PHOTOS.mugHands,
      photoCaption: "Вручение за завтраком",
      history: [
        { label: "Принят", at: "26 июл", done: true },
        { label: "В работе", at: "26 июл", done: true },
        { label: "Готов", at: "27 июл", done: true },
        { label: "Вручен", at: "28 июл", done: true },
      ],
      previewReview: {
        author: "Аня",
        text: "Мама расплакалась. Портрет получился нежным, как просили.",
        emotion: "Слёзы счастья",
      },
    },
    {
      id: "ord-live-02",
      giftId: "idea-01",
      giftTitle: "Кружка-карикатура рыбаку",
      giftHref: "/gift?id=idea-01",
      orderSameHref: "/gift?id=idea-01",
      recipientName: "Игорь",
      recipientRole: "Папа",
      total: 1890,
      completedAt: "2026-07-30",
      completedLabel: "30 июля",
      photoUrl: HOME_PHOTOS.mugWarm,
      photoCaption: "Смеётся до слёз",
      history: [
        { label: "Принят", at: "29 июл", done: true },
        { label: "В работе", at: "29 июл", done: true },
        { label: "Готов", at: "30 июл", done: true },
        { label: "Вручен", at: "30 июл", done: true },
      ],
      previewReview: {
        author: "Сергей",
        text: "Папа орёт от смеха до сих пор. Упаковка огонь.",
        emotion: "В восторге",
      },
    },
    {
      id: "ord-live-03",
      giftId: "canvas",
      giftTitle: "Холст в стиле Pixar",
      giftHref: "/gift?id=canvas",
      orderSameHref: "/gift?id=canvas",
      recipientName: "Марина",
      recipientRole: "Девушка",
      total: 4590,
      completedAt: "2026-08-01",
      completedLabel: "1 августа",
      photoUrl: HOME_PHOTOS.coupleGift,
      photoCaption: "Вау при вручении",
      history: [
        { label: "Принят", at: "30 июл", done: true },
        { label: "В работе", at: "30 июл", done: true },
        { label: "Готов", at: "31 июл", done: true },
        { label: "Вручен", at: "1 авг", done: true },
      ],
      previewReview: {
        author: "Дима",
        text: "Вау при вручении. Она сначала не поняла, что это мы.",
        emotion: "Вау",
      },
    },
    {
      id: "ord-live-04",
      giftId: "tee",
      giftTitle: "Футболка с комикс-принтом",
      giftHref: "/gift?id=tee",
      orderSameHref: "/gift?id=tee",
      recipientName: "Кирилл",
      recipientRole: "Брат",
      total: 2790,
      completedAt: "2026-08-02",
      completedLabel: "2 августа",
      photoUrl: HOME_PHOTOS.teeWear,
      photoCaption: "Надел сразу",
      history: [
        { label: "Принят", at: "1 авг", done: true },
        { label: "В работе", at: "1 авг", done: true },
        { label: "Готов", at: "2 авг", done: true },
        { label: "Вручен", at: "2 авг", done: true },
      ],
      previewReview: {
        author: "Лена",
        text: "Брат в ней уже третий день. Размер сел идеально.",
        emotion: "Идеально",
      },
    },
    {
      id: "ord-live-05",
      giftId: "puzzle",
      giftTitle: "Пазл с семейным фото",
      giftHref: "/gift?id=puzzle",
      orderSameHref: "/gift?id=puzzle",
      recipientName: "Семья Петровых",
      recipientRole: "Семья",
      total: 3290,
      completedAt: "2026-08-03",
      completedLabel: "3 августа",
      photoUrl: HOME_PHOTOS.familyTable,
      photoCaption: "Вечер за пазлом",
      history: [
        { label: "Принят", at: "1 авг", done: true },
        { label: "В работе", at: "2 авг", done: true },
        { label: "Готов", at: "3 авг", done: true },
        { label: "Вручен", at: "3 авг", done: true },
      ],
      previewReview: {
        author: "Катя",
        text: "Собрали всей семьёй. Лучший подарок на новоселье.",
        emotion: "Тепло",
      },
    },
  ],
  reviews: [
    {
      id: "rev-01",
      author: "Аня",
      text: "Мама расплакалась. Портрет получился нежным, как просили.",
      emotion: "Слёзы счастья",
      rating: 5,
      giftId: "mug",
      giftTitle: "Кружка с акварельным портретом",
      giftHref: "/gift?id=mug",
      photoUrl: HOME_PHOTOS.mugHands,
      createdAt: "2026-07-28",
      createdLabel: "28 июля",
    },
    {
      id: "rev-02",
      author: "Сергей",
      text: "Папа орёт от смеха до сих пор. Упаковка огонь.",
      emotion: "В восторге",
      rating: 5,
      giftId: "idea-01",
      giftTitle: "Кружка-карикатура рыбаку",
      giftHref: "/gift?id=idea-01",
      photoUrl: HOME_PHOTOS.mugWarm,
      createdAt: "2026-07-30",
      createdLabel: "30 июля",
    },
    {
      id: "rev-03",
      author: "Дима",
      text: "Вау при вручении. Она сначала не поняла, что это мы.",
      emotion: "Вау",
      rating: 5,
      giftId: "canvas",
      giftTitle: "Холст в стиле Pixar",
      giftHref: "/gift?id=canvas",
      photoUrl: HOME_PHOTOS.coupleGift,
      createdAt: "2026-08-01",
      createdLabel: "1 августа",
    },
    {
      id: "rev-04",
      author: "Лена",
      text: "Брат в ней уже третий день. Размер сел идеально.",
      emotion: "Идеально",
      rating: 5,
      giftId: "tee",
      giftTitle: "Футболка с комикс-принтом",
      giftHref: "/gift?id=tee",
      photoUrl: HOME_PHOTOS.teeWear,
      createdAt: "2026-08-02",
      createdLabel: "2 августа",
    },
    {
      id: "rev-05",
      author: "Катя",
      text: "Собрали всей семьёй. Лучший подарок на новоселье.",
      emotion: "Тепло",
      rating: 5,
      giftId: "puzzle",
      giftTitle: "Пазл с семейным фото",
      giftHref: "/gift?id=puzzle",
      photoUrl: HOME_PHOTOS.familyTable,
      createdAt: "2026-08-03",
      createdLabel: "3 августа",
    },
    {
      id: "rev-06",
      author: "Ирина",
      text: "Корпоративные кружки пришли вовремя, макет согласовали за час.",
      emotion: "Надёжно",
      rating: 5,
      giftId: "mug",
      giftTitle: "Кружка с логотипом",
      giftHref: "/gift?id=mug",
      photoUrl: HOME_PHOTOS.officeMerch,
      createdAt: "2026-08-04",
      createdLabel: "4 августа",
    },
  ],
  popularGifts: [
    {
      giftId: "mug",
      title: "Кружка",
      href: "/gift?id=mug",
      imageUrl: HOME_PHOTOS.mugHands,
      orderCount: 1240,
      rating: 4.9,
    },
    {
      giftId: "tee",
      title: "Футболка",
      href: "/gift?id=tee",
      imageUrl: HOME_PHOTOS.teeWear,
      orderCount: 890,
      rating: 4.8,
    },
    {
      giftId: "canvas",
      title: "Холст",
      href: "/gift?id=canvas",
      imageUrl: HOME_PHOTOS.canvasWall,
      orderCount: 760,
      rating: 5.0,
    },
    {
      giftId: "puzzle",
      title: "Пазл",
      href: "/gift?id=puzzle",
      imageUrl: HOME_PHOTOS.familyTable,
      orderCount: 420,
      rating: 4.9,
    },
    {
      giftId: "photo",
      title: "Фотопечать",
      href: "/photo",
      imageUrl: HOME_PHOTOS.photoPrint,
      orderCount: 1100,
      rating: 4.8,
    },
    {
      giftId: "business",
      title: "Для бизнеса",
      href: "/business",
      imageUrl: HOME_PHOTOS.officeMerch,
      orderCount: 340,
      rating: 4.9,
    },
  ],
  clientPhotos: [
    {
      id: "ph-01",
      imageUrl: HOME_PHOTOS.smileOpen,
      caption: "Радость в момент открытия",
      author: "Марина",
      giftId: "canvas",
      giftHref: "/gift?id=canvas",
      giftTitle: "Холст",
    },
    {
      id: "ph-02",
      imageUrl: HOME_PHOTOS.mugHands,
      caption: "Утренний кофе с портретом",
      author: "Аня",
      giftId: "mug",
      giftHref: "/gift?id=mug",
      giftTitle: "Кружка",
    },
    {
      id: "ph-03",
      imageUrl: HOME_PHOTOS.familyTable,
      caption: "Весь вечер за пазлом",
      author: "Катя",
      giftId: "puzzle",
      giftHref: "/gift?id=puzzle",
      giftTitle: "Пазл",
    },
    {
      id: "ph-04",
      imageUrl: HOME_PHOTOS.birthday,
      caption: "Сюрприз на день рождения",
      author: "Олег",
      giftId: "tee",
      giftHref: "/gift?id=tee",
      giftTitle: "Футболка",
    },
    {
      id: "ph-05",
      imageUrl: HOME_PHOTOS.packing,
      caption: "Упаковка как часть подарка",
      author: "Света",
      giftId: "mug",
      giftHref: "/gift?id=mug",
      giftTitle: "Кружка",
    },
    {
      id: "ph-06",
      imageUrl: HOME_PHOTOS.coupleGift,
      caption: "Годовщина — вау-эффект",
      author: "Дима",
      giftId: "canvas",
      giftHref: "/gift?id=canvas",
      giftTitle: "Холст",
    },
  ],
  stories: [
    {
      id: "st-01",
      title: "Мама не верила, что это её портрет",
      body: "Заказывали кружку к юбилею. Прислали фото за день до — согласовали тон кожи и причёску. Вручили за завтраком: мама сначала молчала, потом плакала и смеялась одновременно. Теперь кружка только её.",
      author: "Аня К.",
      recipientRole: "Мама",
      imageUrl: HOME_PHOTOS.mugHands,
      giftId: "mug",
      giftHref: "/gift?id=mug",
      giftTitle: "Кружка с акварельным портретом",
      rating: 5,
    },
    {
      id: "st-02",
      title: "Холст на годовщину — она не узнала нас сразу",
      body: "Стиль Pixar, наше общее фото с поездки. Повесили в гостиной в тот же вечер. Соседи спрашивают, где заказывали. Заказывали здесь — от идеи до доставки за три дня.",
      author: "Дима и Марина",
      recipientRole: "Пара",
      imageUrl: HOME_PHOTOS.coupleGift,
      giftId: "canvas",
      giftHref: "/gift?id=canvas",
      giftTitle: "Холст в стиле Pixar",
      rating: 5,
    },
    {
      id: "st-03",
      title: "Семейный пазл стал традицией воскресений",
      body: "На новоселье подарили пазл с семейным снимком. Собрали за два вечера, теперь стоит в рамке в прихожей. Уже заказали второй — для бабушки.",
      author: "Катя П.",
      recipientRole: "Семья",
      imageUrl: HOME_PHOTOS.familyTable,
      giftId: "puzzle",
      giftHref: "/gift?id=puzzle",
      giftTitle: "Пазл с семейным фото",
      rating: 5,
    },
  ],
};
