import type { InspirationIdea, InspirationSource } from "./types";

/**
 * Seed catalog for Inspiration Engine (mock).
 * Real works / AI generations can plug into the same shape later.
 */
export const INSPIRATION_CATALOG: InspirationIdea[] = [
  {
    id: "insp-mug-mom-watercolor",
    title: "Кружка маме · акварель",
    subtitle: "Тёплый портрет на утреннем кофе",
    emoji: "☕",
    tone: "from-[#a8d8ea] to-[#7ab8d4]",
    sources: ["category", "occasion", "style"],
    category: "mug",
    style: "Акварель",
    occasion: "День рождения",
    recipient: "Мама",
    popularity: 92,
    createHref: "/design?product=mug&style=watercolor&q=" + encodeURIComponent("Подарок маме акварель"),
  },
  {
    id: "insp-mug-caricature",
    title: "Кружка с карикатурой",
    subtitle: "Юмор, который дарят снова",
    emoji: "😄",
    tone: "from-[#ffb4a2] to-[#ff5a3c]",
    sources: ["category", "style", "popular"],
    category: "mug",
    style: "Карикатура",
    occasion: "Без повода",
    recipient: "Друг",
    popularity: 88,
    createHref: "/design?product=mug&style=caricature&q=" + encodeURIComponent("Кружка карикатура"),
  },
  {
    id: "insp-canvas-pixar",
    title: "Холст Pixar",
    subtitle: "Вау при вручении",
    emoji: "🖼️",
    tone: "from-[#f7b6c8] to-[#e84d6f]",
    sources: ["category", "style", "ai", "popular"],
    category: "canvas",
    style: "Pixar",
    occasion: "Годовщина",
    recipient: "Девушка",
    popularity: 95,
    createHref: "/design?product=canvas&style=pixar&q=" + encodeURIComponent("Холст Pixar портрет"),
  },
  {
    id: "insp-canvas-minimal",
    title: "Холст минимализм",
    subtitle: "Чисто, дорого, спокойно",
    emoji: "✨",
    tone: "from-[#f0e6dc] to-[#d4c4b0]",
    sources: ["category", "style"],
    category: "canvas",
    style: "Минимализм",
    occasion: "Новый год",
    recipient: "Коллега",
    popularity: 70,
    createHref: "/design?product=canvas&style=minimal&q=" + encodeURIComponent("Холст минимализм"),
  },
  {
    id: "insp-tee-comic",
    title: "Футболка комикс",
    subtitle: "Принт как кадр из истории",
    emoji: "👕",
    tone: "from-[#ffd59a] to-[#ff9f43]",
    sources: ["category", "style", "popular"],
    category: "tee",
    style: "Комикс",
    occasion: "День рождения",
    recipient: "Брат",
    popularity: 84,
    createHref: "/design?product=tee&style=comic&q=" + encodeURIComponent("Футболка комикс"),
  },
  {
    id: "insp-tee-boss",
    title: "Футболка начальнику",
    subtitle: "Сдержанный корпоративный вайб",
    emoji: "👔",
    tone: "from-[#e8d4c4] to-[#8b6914]",
    sources: ["recipient", "occasion", "category"],
    category: "tee",
    style: "Минимализм",
    occasion: "Благодарность",
    recipient: "Начальник",
    popularity: 61,
    createHref: "/ideas?q=" + encodeURIComponent("Подарок начальнику футболка"),
  },
  {
    id: "insp-puzzle-family",
    title: "Пазл семье",
    subtitle: "Общее фото — общий вечер",
    emoji: "🧩",
    tone: "from-[#9de7c8] to-[#3db88a]",
    sources: ["category", "occasion", "popular"],
    category: "puzzle",
    style: "Реализм",
    occasion: "Семья",
    recipient: "Семья",
    popularity: 77,
    createHref: "/design?product=puzzle&q=" + encodeURIComponent("Пазл с фото семьи"),
  },
  {
    id: "insp-ai-surprise",
    title: "Удиви меня",
    subtitle: "Стиль подберём за вас",
    emoji: "🎲",
    tone: "from-[#ffc9b0] to-[#ff5a3c]",
    sources: ["ai", "popular"],
    category: "any",
    style: "Сюрприз",
    occasion: "Любой",
    recipient: "Любой",
    popularity: 90,
    createHref: "/design?mode=surprise",
  },
  {
    id: "insp-girl-anime",
    title: "Аниме для девушки",
    subtitle: "Нежный персонаж с фото",
    emoji: "🌸",
    tone: "from-[#c8e8ff] to-[#7ab8e8]",
    sources: ["recipient", "style", "ai"],
    category: "canvas",
    style: "Anime",
    occasion: "Годовщина",
    recipient: "Девушка",
    popularity: 86,
    createHref: "/design?product=canvas&style=anime&q=" + encodeURIComponent("Подарок девушке аниме"),
  },
  {
    id: "insp-teacher-set",
    title: "Набор учителю",
    subtitle: "Кружка + чай + открытка",
    emoji: "📚",
    tone: "from-[#ffd59a] to-[#ff9f43]",
    sources: ["recipient", "occasion", "popular"],
    category: "mug",
    style: "Акварель",
    occasion: "Конец года",
    recipient: "Учитель",
    popularity: 73,
    createHref: "/ideas?q=" + encodeURIComponent("Подарок учителю набор"),
  },
  {
    id: "insp-wedding-frame",
    title: "Свадебная рамка",
    subtitle: "Дата и имена навсегда",
    emoji: "💍",
    tone: "from-[#ffd0dc] to-[#e86a8a]",
    sources: ["occasion", "category"],
    category: "frame",
    style: "Минимализм",
    occasion: "Свадьба",
    recipient: "Пара",
    popularity: 68,
    createHref:
      "/design?product=frame&style=minimal&q=" +
      encodeURIComponent("Свадебная рамка"),
  },
  {
    id: "insp-dad-fish",
    title: "Папе рыбаку",
    subtitle: "Кружка + юмор под хобби",
    emoji: "🎣",
    tone: "from-[#9ad8ff] to-[#3d9fd8]",
    sources: ["recipient", "ai", "popular"],
    category: "mug",
    style: "Карикатура",
    occasion: "День рождения",
    recipient: "Папа",
    popularity: 81,
    createHref: "/ideas?q=" + encodeURIComponent("Подарок папе рыбаку до 3000"),
  },
];

export const SOURCE_LABELS: Record<InspirationSource, string> = {
  category: "Категория",
  style: "Стиль",
  occasion: "Повод",
  recipient: "Получатель",
  ai: "Подбор",
  popular: "Популярное",
};
