export type GiftIdea = {
  id: string;
  title: string;
  description: string;
  price: number;
  leadTime: string;
  recipient: string;
  occasion: string;
  budget: string;
  technology: string;
  style: string;
  gradient: string;
  emoji: string;
};

export const FILTER_OPTIONS = {
  recipient: ["Брат", "Сестра", "Мама", "Папа", "Девушка", "Ребёнок", "Коллега"],
  occasion: ["День рождения", "Годовщина", "Новый год", "Без повода", "Благодарность"],
  budget: ["до 1000 ₽", "1000–3000 ₽", "3000–7000 ₽", "от 7000 ₽"],
  technology: ["Сублимация", "Текстиль", "Фотопечать", "Гравировка", "Набор"],
  style: ["Карикатура", "Pixar", "Комикс", "Акварель", "Поп-арт", "Минимализм", "Неон"],
} as const;

export const MOCK_IDEAS: GiftIdea[] = [
  {
    id: "idea-01",
    title: "Кружка «Брат навсегда»",
    description: "Яркая карикатура на кружке — юмор и тепло в одном подарке.",
    price: 990,
    leadTime: "1–2 дня",
    recipient: "Брат",
    occasion: "День рождения",
    budget: "до 1000 ₽",
    technology: "Сублимация",
    style: "Карикатура",
    gradient: "from-[#ffb4a2] to-[#ff5a3c]",
    emoji: "☕",
  },
  {
    id: "idea-02",
    title: "Футболка в стиле комикс",
    description: "Персональный принт в комикс-стиле — заметный и весёлый подарок.",
    price: 1690,
    leadTime: "2–3 дня",
    recipient: "Брат",
    occasion: "Без повода",
    budget: "1000–3000 ₽",
    technology: "Текстиль",
    style: "Комикс",
    gradient: "from-[#ffd59a] to-[#ff9f43]",
    emoji: "👕",
  },
  {
    id: "idea-03",
    title: "Холст Pixar-портрет",
    description: "Тёплый мультяшный портрет на холсте — вау-эффект при вручении.",
    price: 2490,
    leadTime: "2–3 дня",
    recipient: "Девушка",
    occasion: "Годовщина",
    budget: "1000–3000 ₽",
    technology: "Фотопечать",
    style: "Pixar",
    gradient: "from-[#f7b6c8] to-[#e84d6f]",
    emoji: "🖼️",
  },
  {
    id: "idea-04",
    title: "Набор «Уютный вечер»",
    description: "Кружка + свеча + шоколад + открытка в красивой упаковке.",
    price: 2990,
    leadTime: "2–4 дня",
    recipient: "Мама",
    occasion: "Благодарность",
    budget: "1000–3000 ₽",
    technology: "Набор",
    style: "Акварель",
    gradient: "from-[#9de7c8] to-[#3db88a]",
    emoji: "🎁",
  },
  {
    id: "idea-05",
    title: "Магниты с семейными фото",
    description: "Набор магнитов с тёплыми моментами — просто и трогательно.",
    price: 890,
    leadTime: "1–2 дня",
    recipient: "Мама",
    occasion: "Без повода",
    budget: "до 1000 ₽",
    technology: "Фотопечать",
    style: "Минимализм",
    gradient: "from-[#c9ddff] to-[#6b9dff]",
    emoji: "🧲",
  },
  {
    id: "idea-06",
    title: "Неоновая футболка",
    description: "Смелый неон-принт для тех, кто любит выделяться.",
    price: 1890,
    leadTime: "2–3 дня",
    recipient: "Брат",
    occasion: "День рождения",
    budget: "1000–3000 ₽",
    technology: "Текстиль",
    style: "Неон",
    gradient: "from-[#d4b8ff] to-[#8b5cf6]",
    emoji: "✨",
  },
  {
    id: "idea-07",
    title: "Поп-арт постер",
    description: "Крупный яркий постер в стиле поп-арт — акцент на стену.",
    price: 1590,
    leadTime: "2 дня",
    recipient: "Сестра",
    occasion: "День рождения",
    budget: "1000–3000 ₽",
    technology: "Фотопечать",
    style: "Поп-арт",
    gradient: "from-[#ffc2e0] to-[#ff5a9a]",
    emoji: "🎨",
  },
  {
    id: "idea-08",
    title: "Гравированная доска папе",
    description: "Именная разделочная доска с датой и короткой подписью.",
    price: 2490,
    leadTime: "2–4 дня",
    recipient: "Папа",
    occasion: "День рождения",
    budget: "1000–3000 ₽",
    technology: "Гравировка",
    style: "Минимализм",
    gradient: "from-[#e8d5b7] to-[#c4a574]",
    emoji: "🪵",
  },
  {
    id: "idea-09",
    title: "Детский пазл Pixar",
    description: "Пазл с мультяшным портретом ребёнка — игра и память вместе.",
    price: 1490,
    leadTime: "3 дня",
    recipient: "Ребёнок",
    occasion: "День рождения",
    budget: "1000–3000 ₽",
    technology: "Фотопечать",
    style: "Pixar",
    gradient: "from-[#ffe08a] to-[#ffb703]",
    emoji: "🧩",
  },
  {
    id: "idea-10",
    title: "Акварельный холст маме",
    description: "Нежный акварельный портрет — подарок с эмоцией и вкусом.",
    price: 2790,
    leadTime: "2–3 дня",
    recipient: "Мама",
    occasion: "День рождения",
    budget: "1000–3000 ₽",
    technology: "Фотопечать",
    style: "Акварель",
    gradient: "from-[#b8e0ff] to-[#74b9ff]",
    emoji: "🖌️",
  },
  {
    id: "idea-11",
    title: "Офисный набор коллеге",
    description: "Минималистичная кружка и открытка — универсально и стильно.",
    price: 1290,
    leadTime: "1–2 дня",
    recipient: "Коллега",
    occasion: "Благодарность",
    budget: "1000–3000 ₽",
    technology: "Набор",
    style: "Минимализм",
    gradient: "from-[#dfe6e9] to-[#b2bec3]",
    emoji: "🏢",
  },
  {
    id: "idea-12",
    title: "Премиум-набор на годовщину",
    description: "Холст + рамка + шоколад + открытка в праздничной упаковке.",
    price: 4990,
    leadTime: "3–5 дней",
    recipient: "Девушка",
    occasion: "Годовщина",
    budget: "3000–7000 ₽",
    technology: "Набор",
    style: "Акварель",
    gradient: "from-[#f8c8dc] to-[#e84393]",
    emoji: "💝",
  },
];

export function formatPrice(price: number) {
  return `${price.toLocaleString("ru-RU")} ₽`;
}
