import { computeGiftScore } from "./score";
import type { GiftScoreMetrics } from "./types";

function row(
  partial: Omit<GiftScoreMetrics, "score">,
): GiftScoreMetrics {
  return {
    ...partial,
    score: computeGiftScore(partial),
  };
}

/** Mock Gift Score catalog — replace with real counters later */
export const GIFT_SCORE_MOCK: GiftScoreMetrics[] = [
  row({
    giftId: "mug",
    title: "Кружка с фото",
    emoji: "☕",
    tone: "from-[#ffb4a2] to-[#ff6b4a]",
    href: "/gift?id=mug",
    stars: 4.9,
    orders: 420,
    likes: 1860,
    saves: 640,
    reviews: 158,
    repeats: 72,
    ordersWeek: 48,
    ordersMonth: 160,
    ordersYear: 420,
    growthRate: 1.8,
    commentsCount: 94,
    unusualScore: 12,
  }),
  row({
    giftId: "canvas",
    title: "Холст-портрет",
    emoji: "🖼️",
    tone: "from-[#f7b6c8] to-[#e84d6f]",
    href: "/gift?id=canvas",
    stars: 4.8,
    orders: 310,
    likes: 2100,
    saves: 890,
    reviews: 122,
    repeats: 41,
    ordersWeek: 36,
    ordersMonth: 118,
    ordersYear: 310,
    growthRate: 2.4,
    commentsCount: 110,
    unusualScore: 28,
  }),
  row({
    giftId: "tee",
    title: "Футболка с принтом",
    emoji: "👕",
    tone: "from-[#ffd59a] to-[#ff9f43]",
    href: "/gift?id=tee",
    stars: 4.6,
    orders: 380,
    likes: 1420,
    saves: 510,
    reviews: 98,
    repeats: 55,
    ordersWeek: 52,
    ordersMonth: 140,
    ordersYear: 380,
    growthRate: 1.5,
    commentsCount: 67,
    unusualScore: 18,
  }),
  row({
    giftId: "puzzle",
    title: "Пазл с фото",
    emoji: "🧩",
    tone: "from-[#9de7c8] to-[#3db88a]",
    href: "/gift?id=puzzle",
    stars: 4.7,
    orders: 190,
    likes: 980,
    saves: 420,
    reviews: 64,
    repeats: 22,
    ordersWeek: 41,
    ordersMonth: 95,
    ordersYear: 190,
    growthRate: 3.1,
    commentsCount: 88,
    unusualScore: 45,
  }),
  row({
    giftId: "idea-03",
    title: "Холст Pixar-портрет",
    emoji: "🖼️",
    tone: "from-[#f7b6c8] to-[#e84d6f]",
    href: "/gift?id=idea-03",
    stars: 4.9,
    orders: 145,
    likes: 2400,
    saves: 1100,
    reviews: 81,
    repeats: 19,
    ordersWeek: 28,
    ordersMonth: 70,
    ordersYear: 145,
    growthRate: 2.9,
    commentsCount: 156,
    unusualScore: 62,
  }),
  row({
    giftId: "idea-01",
    title: "Кружка «Брат навсегда»",
    emoji: "☕",
    tone: "from-[#ffb4a2] to-[#ff5a3c]",
    href: "/gift?id=idea-01",
    stars: 4.5,
    orders: 260,
    likes: 1100,
    saves: 380,
    reviews: 74,
    repeats: 48,
    ordersWeek: 22,
    ordersMonth: 88,
    ordersYear: 260,
    growthRate: 1.2,
    commentsCount: 41,
    unusualScore: 22,
  }),
  row({
    giftId: "frame",
    title: "Фоторамка",
    emoji: "🖼️",
    tone: "from-[#ffc4b0] to-[#d96b4c]",
    href: "/gift?id=frame",
    stars: 4.3,
    orders: 120,
    likes: 540,
    saves: 210,
    reviews: 33,
    repeats: 14,
    ordersWeek: 31,
    ordersMonth: 55,
    ordersYear: 120,
    growthRate: 3.6,
    commentsCount: 29,
    unusualScore: 15,
  }),
  row({
    giftId: "print_3d_fig",
    title: "3D фигурка",
    emoji: "🧸",
    tone: "from-[#ffc4b0] to-[#d96b4c]",
    href: "/create?scenario=print_3d",
    stars: 4.4,
    orders: 68,
    likes: 720,
    saves: 390,
    reviews: 27,
    repeats: 8,
    ordersWeek: 19,
    ordersMonth: 40,
    ordersYear: 68,
    growthRate: 4.2,
    commentsCount: 73,
    unusualScore: 88,
  }),
  row({
    giftId: "laser_board",
    title: "Лазерная гравировка",
    emoji: "🪵",
    tone: "from-[#e8c4a8] to-[#a67c52]",
    href: "/create?scenario=laser",
    stars: 4.6,
    orders: 95,
    likes: 610,
    saves: 280,
    reviews: 39,
    repeats: 11,
    ordersWeek: 14,
    ordersMonth: 42,
    ordersYear: 95,
    growthRate: 2.1,
    commentsCount: 52,
    unusualScore: 71,
  }),
  row({
    giftId: "idea-04",
    title: "Набор «Уютный вечер»",
    emoji: "🎁",
    tone: "from-[#9de7c8] to-[#3db88a]",
    href: "/gift?id=idea-04",
    stars: 4.8,
    orders: 205,
    likes: 1340,
    saves: 560,
    reviews: 91,
    repeats: 36,
    ordersWeek: 33,
    ordersMonth: 102,
    ordersYear: 205,
    growthRate: 1.9,
    commentsCount: 60,
    unusualScore: 25,
  }),
];

export function getGiftScore(giftId: string): GiftScoreMetrics | null {
  const key = giftId.trim().toLowerCase();
  return (
    GIFT_SCORE_MOCK.find(
      (item) =>
        item.giftId.toLowerCase() === key ||
        item.href.includes(`id=${giftId}`),
    ) ?? null
  );
}

export function getGiftScoreOrFallback(
  giftId: string,
  fallback?: { title: string; emoji: string; tone: string },
): GiftScoreMetrics {
  const found = getGiftScore(giftId);
  if (found) return found;
  return row({
    giftId,
    title: fallback?.title ?? giftId,
    emoji: fallback?.emoji ?? "🎁",
    tone: fallback?.tone ?? "from-[#ffb4a2] to-[#ff5a3c]",
    href: `/gift?id=${encodeURIComponent(giftId)}`,
    stars: 4.5,
    orders: 12,
    likes: 40,
    saves: 18,
    reviews: 5,
    repeats: 1,
    ordersWeek: 3,
    ordersMonth: 8,
    ordersYear: 12,
    growthRate: 1,
    commentsCount: 4,
    unusualScore: 10,
  });
}
